apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: python-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-docker
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80